// @ts-check
/**
 * POST /api/auth/figma — initiates the Figma OAuth flow.
 *
 * Request body: `{ figmaUserId, state }` — both required. `state` must be a
 * UUID v4 generated by the plugin. Returns `{ url }` for the plugin to open.
 */

import supabase from "../../lib/supabase.js";
import { applyCors, withErrorHandling } from "../../lib/http.js";
import { logger } from "../../lib/logger.js";
import { assertFigmaUserId, assertUuid } from "../../lib/validators.js";
import { ValidationError } from "../../lib/errors.js";

const SCOPES = "files:read,webhooks:write";

export default withErrorHandling(
  /**
   * @param {import("../../lib/types.js").VercelRequest} req
   * @param {import("../../lib/types.js").VercelResponse} res
   */
  async function handler(req, res) {
    if (applyCors(req, res)) return;
    if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

    const body = /** @type {Record<string, unknown> | null} */ (req.body) ?? {};
    const state = assertUuid(body.state);
    const figmaUserId = assertFigmaUserId(body.figmaUserId);

    const { error } = await supabase.from("auth_sessions").upsert(
      {
        state,
        provider: "figma",
        figma_user_id: figmaUserId,
        status: "pending",
        expires_at: new Date(Date.now() + 10 * 60 * 1000).toISOString(),
        used_at: null,
        result_data: {},
      },
      { onConflict: "state" },
    );

    if (error) {
      logger.error("auth_session_create_failed", { provider: "figma", err: error });
      // Surface the underlying DB cause (e.g. a missing column from an
      // un-migrated schema) instead of a generic message — this endpoint is
      // only ever hit by the installer's own plugin, so a precise error is
      // worth far more than hiding it. See database/migrations/002.
      throw new ValidationError(
        `Could not create auth session: ${error.message || error.code || "database error"}`,
      );
    }

    const redirectUri = `${envOrThrow("PUBLIC_URL")}/api/auth/figma-callback`;
    const url = new URL("https://www.figma.com/oauth");
    url.searchParams.set("client_id", envOrThrow("FIGMA_CLIENT_ID"));
    url.searchParams.set("redirect_uri", redirectUri);
    url.searchParams.set("scope", SCOPES);
    url.searchParams.set("state", state);
    url.searchParams.set("response_type", "code");

    return res.status(200).json({ url: url.toString() });
  },
);

/** @param {string} name */
function envOrThrow(name) {
  const v = process.env[name];
  if (!v) throw new ValidationError(`Missing env: ${name}`);
  return v;
}
